language: python

addons:
  postgresql: "10"

services:
  - docker
  - postgresql

python:
  - "3.6"

cache: pip

before_script:
  - psql -c 'create database doccano;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - tools/ci.sh

deploy:
  - provider: script
    script: tools/cd.sh
    on:
      repo: Honeyfy/doccano
      tags: true
